apiVersion: v1
kind: Service
metadata:
  name: auth-backend-service
  labels:
    app: auth-backend
spec:
  type: NodePort
  selector:
    app: auth-backend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
    protocol: TCP